name: Test

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubunti-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKE ${{ secrets.GITHUB_TOKEN }}